title: Jacob Ard's ePortfolio
description: SNHU CS-499 Capstone
#remote_theme: pages-themes/modernist@v0.2.0
remote_theme: "jekyll/minima@2.5-stable"

plugins:
- jekyll-remote-theme 
- jekyll-include-cache

header_pages:
  - index.md
  - pages/code-review.md
  - pages/travlr.md
  - pages/course-list.md
  - pages/aac-dashboard.md
