title: Jacob Ard's ePortfolio
description: SNHU CS-499 Capstone
#remote_theme: pages-themes/modernist@v0.2.0
remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
- jekyll-remote-theme 
- jekyll-include-cache

nav_enabled: true
enable_heading_anchors: true
